package com.example.nextlayer.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF006C4C)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF89F8C7)
val OnPrimaryContainer = Color(0xFF002114)
val Secondary = Color(0xFF4C6357)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFCEE9D9)
val OnSecondaryContainer = Color(0xFF092016)
val Tertiary = Color(0xFF3D6373)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFC1E8FB)
val OnTertiaryContainer = Color(0xFF001F29)
val Error = Color(0xFFBA1A1A)
val ErrorContainer = Color(0xFFFFDAD6)
val OnError = Color(0xFFFFFFFF)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFFBFDF9)
val OnBackground = Color(0xFF191C1A)
val Surface = Color(0xFFFBFDF9)
val OnSurface = Color(0xFF191C1A)
val SurfaceVariant = Color(0xFFDBE5DD)
val OnSurfaceVariant = Color(0xFF404943)
val Outline = Color(0xFF707973)
val InverseOnSurface = Color(0xFFEFF1ED)
val InverseSurface = Color(0xFF2E312F)
val InversePrimary = Color(0xFF6CDBAB)
