name: Android CI Build (Debug)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.3.1'

      - name: Create debug keystore
        run: |
          keytool -genkeypair \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 \
            -validity 10000 \
            -storepass android -keypass android \
            -keystore debug.keystore \
            -dname "CN=Android Debug,O=Android,C=US"

      # Ganti ./gradlew jadi gradle (panggil gradle dari sistem runner)
      - name: Build Debug APK
        run: gradle assembleDebug --stacktrace

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
